### ISSUE TITLE
bug(brewfile): syntax error in extra/brew/brewfile

### ISSUE THREAD

**Issue by kisstupid** [shaunsingh/vimrc-dotfiles#1]
Error: Invalid Brewfile: (eval):7: syntax error, unexpected tIDENTIFIER, expecting end-of-input.

`tap "koekeishiya/formulae"a`

Please remove `a` character in this line.

**Comment by shaunsingh** [comment]
Fixed, thank you for reporting it. Let me know if you need anything else
