### ISSUE TITLE
yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -1708

### ISSUE THREAD

**Issue by liamrohan** [shaunsingh/vimrc-dotfiles#25]
@shaunsingh thanks so much for creating this. 

Don't suppose you've experienced this at all? Have created a new user with zero config and this error still persists. 

```nix
services.yabai = {
#...
    enableScriptingAddition = true;
#...
}
```

The above seems to create a `launchd` agent at `~/Library/LaunchAgents/org.nixos.yabai.plist`, which causes `yabai: scripting-addition either failed to load or could not inject payload into Dock.app` every 5s and the screen to flicker.

Have followed [scripting addition configuration](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition) via yabai's wiki though no luck. 

Setting `enableScriptingAddition = false` for now. Apologies if doing something dumb as new to Nix.

**Comment by shaunsingh** [comment]
I don't have the issue on my own machine, but I wouldn't be surprised if it was happening on yours, yabai is very finicky. 

Looks like nixpkgs might bump yabai soon (https://github.com/NixOS/nixpkgs/pull/203504#issuecomment-1331342078) which *should* resolve this issue.
